"""Every number the realistic-conditions write-up quotes, regenerated by this
package and compared against the three frozen legacy outputs
(tests/fixtures/legacy/out-rr-{numbers,map,robust}.json).

The field names mostly carry over unchanged; three are intentionally renamed in
the rebuild (noted below), and two legacy scalars are tolerance-free floats that
the rebuild nests alongside the sweep that produced them. Both are mapped
explicitly rather than guessed at.
"""
import pytest


def _flatten(x, prefix=""):
    if isinstance(x, dict):
        for k, v in x.items():
            yield from _flatten(v, f"{prefix}.{k}" if prefix else k)
    elif isinstance(x, list):
        for i, v in enumerate(x):
            yield from _flatten(v, f"{prefix}[{i}]")
    else:
        yield prefix, x


def _assert_close(old, new, rel=1e-6, abs_=1e-12, where=""):
    if isinstance(old, bool) or isinstance(new, bool):
        assert bool(old) == bool(new), f"{where}: {old!r} != {new!r}"
        return
    if old is None or new is None:
        assert old == new, f"{where}: {old!r} != {new!r}"
        return
    if isinstance(old, (int, float)) and isinstance(new, (int, float)):
        assert new == pytest.approx(old, rel=rel, abs=abs_), f"{where}: {old!r} != {new!r}"
        return
    assert old == new, f"{where}: {old!r} != {new!r}"


def _assert_subset_matches(old, new, where=""):
    """Every leaf in `old` must appear in `new` at the same path, and match."""
    o = dict(_flatten(old))
    n = dict(_flatten(new))
    missing = set(o) - set(n)
    assert not missing, f"{where}: legacy keys missing from the rebuild: {sorted(missing)[:10]}"
    for k, v in o.items():
        _assert_close(v, n[k], where=f"{where}.{k}")


# ---------------------------------------------------------------- stage 2 / out-rr-numbers
def test_stage2_matches_legacy_per_platform(realistic_results, legacy):
    old = legacy["out-rr-numbers"]
    new = realistic_results["stage2_virtual"]["platforms"]
    for key in ("osmium-paul", "torsion-mg", "levitated-gs"):
        _assert_subset_matches(old[key], new[key], where=key)


def test_stage2_controls_match_legacy(realistic_results, legacy):
    _assert_subset_matches(
        legacy["out-rr-numbers"]["controls"], realistic_results["stage2_virtual"]["controls"],
        where="controls",
    )


# ---------------------------------------------------------------- stage 3 / out-rr-map
def test_stage3_mass_independence_matches_legacy(realistic_results, legacy):
    old = legacy["out-rr-map"]["mass_independence"]            # a bare float
    new = realistic_results["stage3_map"]["mass_independence"]["spread"]
    _assert_close(old, new, where="mass_independence")


def test_stage3_corner_matches_legacy(realistic_results, legacy):
    _assert_subset_matches(
        legacy["out-rr-map"]["corner"], realistic_results["stage3_map"]["corner"],
        where="corner",
    )


def test_stage3_platforms_gate_matches_legacy(realistic_results, legacy):
    # renamed: legacy's 'platforms' -> this rebuild's 'platforms_gate', to avoid
    # colliding with stage1's unrelated 'platforms' block in the merged results.
    _assert_subset_matches(
        legacy["out-rr-map"]["platforms"], realistic_results["stage3_map"]["platforms_gate"],
        where="platforms_gate",
    )


def test_stage3_alpha_matches_legacy(realistic_results, legacy):
    # renamed: legacy's 'alpha'/'sqrtV' (computed on V_all) -> this rebuild's
    # 'alpha_all'/'sqrtV_all'; the rebuild adds 'alpha_unc'/'sqrtV_unc' alongside
    # (stage 3 section 7's second half, on the rivals' wide-wavefunction regime),
    # which the legacy json never stored.
    for key in ("osmium-paul", "torsion-mg", "levitated-gs"):
        old = legacy["out-rr-map"]["alpha"][key]
        new = realistic_results["stage3_map"]["alpha"][key]
        _assert_close(old["alpha"], new["alpha_all"], where=f"alpha.{key}.alpha")
        _assert_close(old["sqrtV"], new["sqrtV_all"], where=f"alpha.{key}.sqrtV")


def test_stage3_QT_matches_legacy(realistic_results, legacy):
    for mat in ("silicon", "gold", "tungsten", "osmium"):
        _assert_subset_matches(
            legacy["out-rr-map"]["QT"][mat], realistic_results["stage3_map"]["QT"][mat],
            where=f"QT.{mat}",
        )


def test_stage3_boundary_matches_legacy(realistic_results, legacy):
    _assert_subset_matches(
        legacy["out-rr-map"]["boundary"], realistic_results["stage3_map"]["boundary"],
        where="boundary",
    )


def test_stage3_map_matches_legacy(realistic_results, legacy):
    _assert_subset_matches(
        legacy["out-rr-map"]["map"], realistic_results["stage3_map"]["map"], where="map"
    )


# -------------------------------------------------------------- stage 4 / out-rr-robust
def test_stage4_second_reading_matches_legacy(realistic_results, legacy):
    _assert_subset_matches(
        legacy["out-rr-robust"]["second_reading"],
        realistic_results["stage4_robust"]["second_reading"],
        where="second_reading",
    )


def test_stage4_walls_matches_legacy(realistic_results, legacy):
    _assert_subset_matches(
        legacy["out-rr-robust"]["walls"], realistic_results["stage4_robust"]["walls"],
        where="walls",
    )


def test_stage4_tmin_matches_legacy(realistic_results, legacy):
    old = legacy["out-rr-robust"]["tmin"]
    new = realistic_results["stage4_robust"]["tmin"]
    for key in ("osmium-paul", "torsion-mg", "levitated-gs"):
        _assert_subset_matches(old[key], new[key], where=f"tmin.{key}")
    _assert_subset_matches(
        old["Y25 torsion balance"], new["Y25_torsion_balance"], where="tmin.Y25"
    )


# -------------------------------- stage 1 and 0: no legacy json (text-only originally),
# pinned here from the legacy scripts' own printed output instead.
def test_stage1_baseline_matches_the_original_run(realistic_results):
    b = realistic_results["stage1_platforms"]["baseline"]["osmium-paul"]
    # rr-platforms.py's own stdout, this repository's prior run:
    #   nbar = 2.0837e+08  purity = 2.2562e-09  eta_eff = 0.000000  f = 0.000000
    #   V_unc = 2.2400e-16  V_all = 4.8937e-25  split = 4.2016e-03  G_theory = 3.2402e+01
    assert b["nbar"] == pytest.approx(2.0837e08, rel=1e-4)
    assert b["V_unc"] == pytest.approx(2.2400e-16, rel=1e-4)
    assert b["V_all"] == pytest.approx(4.8937e-25, rel=1e-4)
    assert b["split_theory"] == pytest.approx(4.2016e-03, rel=1e-4)
    assert b["G_theory"] == pytest.approx(3.2402e01, rel=1e-4)


def test_stage0_filter_reproduces_its_two_limits(realistic_results):
    fc = realistic_results["stage0_adapter"]["filter_check"]
    assert fc["V_unconditional"] == pytest.approx(fc["equipartition"], rel=1e-9)
    assert fc["V_conditioned"] == pytest.approx(fc["ground_state"], rel=1e-3)
    assert fc["purity_filter"] == pytest.approx(fc["purity_formula"], rel=1e-9)


def test_stage0_adapter_reduces_to_the_law_exactly(realistic_results):
    assert realistic_results["stage0_adapter"]["eta_eff_check"]["worst"] < 1e-12
    assert realistic_results["stage0_adapter"]["f_reduction_check"]["worst"] < 1e-12
