"""Every number the computational check's write-up quotes, regenerated by this
package and compared against the original experiment's frozen output. The
original is tests/fixtures/legacy/out-rs-numbers.json; every leaf value is
checked, not a sample.
"""


def _flatten(x, prefix=""):
    if isinstance(x, dict):
        for k, v in x.items():
            yield from _flatten(v, f"{prefix}.{k}" if prefix else k)
    elif isinstance(x, list):
        for i, v in enumerate(x):
            yield from _flatten(v, f"{prefix}[{i}]")
    else:
        yield prefix, x


def test_pilot_calibration_matches_the_original_run(check_results):
    # rs-law.py's own stdout, this theory's prior run: "worst absolute difference
    # from the stored targets: 4.71e-05". Not in out-rs-numbers.json (the
    # original script printed it but never wrote it to json), so pinned here
    # from that run rather than compared against a legacy fixture.
    assert check_results["pilot_calibration"]["worst"] < 5e-5


def test_every_leaf_matches_the_legacy_output(check_results, legacy):
    old = dict(_flatten(legacy["out-rs-numbers"]))
    # pilot_calibration is new in this rebuild (the original script printed it
    # but never wrote it to json -- see test_pilot_calibration_matches above),
    # so it is excluded here rather than compared against a legacy fixture.
    new = dict(
        (k, v) for k, v in _flatten(check_results) if not k.startswith("pilot_calibration")
    )

    assert set(old) == set(new), (
        f"key sets differ: missing from new = {sorted(set(old) - set(new))[:10]}, "
        f"new-only = {sorted(set(new) - set(old))[:10]}"
    )

    worst = 0.0
    worst_key = None
    mismatches = []
    for k in old:
        a, b = old[k], new[k]
        if isinstance(a, (int, float)) and isinstance(b, (int, float)):
            d = abs(a - b)
            worst = max(worst, d)
            if d > worst == d:
                worst_key = k
            if d > 1e-6 and abs(a) > 1e-9:
                mismatches.append((k, a, b, d))
        elif a != b:
            mismatches.append((k, a, b, "non-numeric"))

    assert not mismatches, f"{len(mismatches)} mismatches, first few: {mismatches[:10]}"
    # 1e-6, not tighter: this is the same split-step simulation with the same
    # seeds, so it agrees with the legacy run to the arithmetic on any one
    # machine -- but rcg.models.two_mass.concurrence calls np.linalg.eigvals (a
    # non-symmetric eigensolver), whose last 2-3 digits are BLAS-backend
    # dependent. Observed: ~2e-9 absolute between this repository's dev machine
    # and a `uv`-managed environment with a different numpy/LAPACK build, on the
    # same inputs. 1e-9 is too tight to survive that and still be a portable test.
    assert worst < 1e-6, f"worst absolute difference {worst:.3e} at {worst_key!r}"
